### ISSUE TITLE
The laps are blank

### ISSUE THREAD

**Issue by justincbeck** [Isaofmany/StopWatch#2]
![screen shot 2015-12-10 at 4 56 33 pm](https://cloud.githubusercontent.com/assets/95119/11729848/6ee03e32-9f5f-11e5-9a23-68f614222ebd.png)

**Comment by Isaofmany** [comment]
This may be a device issue, I will look into this.

**Comment by Isaofmany** [comment]
This turned out to be a result of inconsistency with default text coloring.  While on my device the text color is visible on a white background, on Nexus and Moto devices the text color needed changing to be visible.  Lesson learned for the future is to give computers even less room to make their own decisions.
