### ISSUE TITLE
Button disable issues

### ISSUE THREAD

**Issue by justincbeck** [Isaofmany/StopWatch#5]
When the clocks are running the start and reset buttons should be disabled
When the clocks are NOT running the start stop and lap buttons should be disabled

**Comment by Isaofmany** [comment]
The start and stop button are disabled until their opposite is pressed, otherwise pressing start would cause the time increment to double with each press.  The reset button I assumed should always be enabled but I will change that.  And I think you meant to say that stop,lap, and reset should be disabled when clock is not running, please correct me if I am wrong.  None the less I will make these changes.
